name: Sync Fork

on:
  schedule:
    - cron: '* 0,4,8,12,16,20 * * *' # every 4 hours
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync alpha (default branch)
        uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: cardano-community
          base: alpha
          head: alpha
      - name: Fork Sync master (production branch)
        uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: cardano-community
          base: master
          head: master
