name: Sync Fork

on:
  schedule:
    - cron: '0 0,8,16 * * *' # every 8 hours
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync alpha (default branch)
        uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: cardano-community
          base: alpha
          head: alpha
          auto_approve: true
          token: ${{ secrets.SYNC_TOKEN }}
      - name: Fork Sync master (production branch)
        uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: cardano-community
          base: master
          head: master
          auto_approve: true
          token: ${{ secrets.SYNC_TOKEN }}
