name: Get Node pre-release version
on:
  workflow_dispatch:
  push:
    branches:
      - alpha
  schedule:
    - cron:  '0 */8 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: preview
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo "GitHub Actor: ${GITHUB_ACTOR}" >> "$GITHUB_STEP_SUMMARY"
          echo "GitHub Email: ${GITHUB_ACTOR}@users.noreply.github.com" >> "$GITHUB_STEP_SUMMARY"
      - name: Fetch node pre-release version
        run: |
          curl -sL https://api.github.com/repos/IntersectMBO/cardano-node/releases | jq -r '.[] | select(.prerelease == true) | .tag_name' | head -1 > files/docker/node/release-versions/cardano-node-prerelease.txt
      - name: Assigns pre-release version
        run: |
          VERSION=$(cat files/docker/node/release-versions/cardano-node-prerelease.txt)
      - name: Check for changes
        id: git-check
        run: |
          export MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo "MODIFIED=${MODIFIED}" >> "$GITHUB_OUTPUT"
          echo "Repository Modified: ${MODIFIED}" >> "$GITHUB_STEP_SUMMARY"  
      - name: Commit latest pre-release versions
        if: steps.git-check.outputs.MODIFIED == 'true'
        run: |
          echo "Modified files: $(git diff --name-only $(jq -r '.sha' "$GITHUB_OUTPUT"))" >> "$GITHUB_STEP_SUMMARY"
          git add files/docker/node/release-versions/cardano-node-prerelease.txt
          git commit -am "New mithril pre-release versions: pre-release ${PRERELEASE_VERSION}"
          git push
