name: Pre-merge Debian

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/guild-deploy.sh
      - scripts/cnode-helper-scripts/cabal-build-all.sh
      - files/tests/pre-merge/debian-guild-deploy.sh.containerfile
      - files/tests/pre-merge/debian-guild-deploy.sh-l.containerfile

jobs:
  guild-deploy-and-build-debian:
    env:
      REGISTRY: ghcr.io
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/share/dotnet"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "/opt/ghc"
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Extract environment variables from PR
      shell: bash
      run: |
        echo "G_ACCOUNT=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
        echo "COMMIT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - name: Workflow Summary
      shell: bash
      run: |
        echo "Premerge testing ${{ env.G_ACCOUNT }}/guild-operators/${BRANCH} for commit ${COMMIT}"
    - name: Testing guild-deploy.sh (IO fork of libsodium)
      run: |
        docker build . --file files/tests/pre-merge/debian-guild-deploy.sh-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --build-arg G_ACCOUNT --tag ghcr.io/${G_ACCOUNT}/pre-merge-debian:guild-deploy-l_${COMMIT}
    - name: Push pre-merge-debian:guild-deploy-l_${COMMIT}
      run: |
        docker push \
          ${{ env.REGISTRY }}/${{ env.G_ACCOUNT }}/pre-merge-debian:guild-deploy-l_${{ env.COMMIT }}
    - name: Testing cabal-build-all.sh (IO fork of libsodium)
      run: |
        docker build . \
          --file files/tests/pre-merge/debian-cabal-l.containerfile \
          --compress \
          --build-arg BRANCH=${{ env.BRANCH }} \
          --build-arg COMMIT=${{ env.COMMIT }} \
          --tag ${{ env.REGISTRY }}/cardano-community/pre-merge-debian:cabal-l_${{ env.COMMIT }}
    - name: Add summary details
      if: always()
      run: |
        echo "## Summary Details" >> $GITHUB_STEP_SUMMARY
        echo "* Docker Image: ${{ env.REGISTRY }}/${{ env.G_ACCOUNT }}/pre-merge-debian:guild-deploy-l_${{ env.COMMIT }}" >> $GITHUB_STEP_SUMMARY
        echo "* BRANCH: ${{ env.BRANCH }}" >> $GITHUB_STEP_SUMMARY
        echo "* G_ACCOUNT: ${{ env.G_ACCOUNT }}" >> $GITHUB_STEP_SUMMARY
        echo "* COMMIT: ${{ env.COMMIT }}" >> $GITHUB_STEP_SUMMARY