name: Pre-merge Debian

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/guild-deploy.sh
      - scripts/cnode-helper-scripts/cabal-build-all.sh
      - files/tests/pre-merge/debian-guild-deploy.sh.containerfile
      - files/tests/pre-merge/debian-guild-deploy.sh-l.containerfile

jobs:
  guild-deploy-and-build-debian:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf "/usr/share/dotnet"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "/opt/ghc"
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract environment variables from PR
      shell: bash
      run: |
        echo "G_ACCOUNT=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
        echo "COMMIT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - name: Workflow Summary
      shell: bash
      run: |
        echo "Premerge testing ${G_ACCOUNT}/guild-operators/${BRANCH} for commit ${COMMIT}"
    - name: Testing guild-deploy.sh (IO fork of libsodium)
      run: |
        docker build . --file files/tests/pre-merge/debian-guild-deploy.sh-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --build-arg G_ACCOUNT --tag ghcr.io/${G_ACCOUNT}/pre-merge-debian:guild-deploy-l_${COMMIT}
    - name: Push pre-merge-debian:guild-deploy-l_${COMMIT}
      run: |
        docker push ghcr.io/${G_ACCOUNT}/pre-merge-debian:guild-deploy-l_${COMMIT}
    - name: Testing cabal-build-all.sh (IO fork of libsodium)
      run: |
        docker build . --file files/tests/pre-merge/debian-cabal-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --tag ghcr.io/cardano-community/pre-merge-debian:cabal-l_${COMMIT}

